// Auto-generated by "solid-vue deploy". Do not edit by hand.
import { app } from '../dist/server-entry.mjs'

export default {
  fetch(request, env, ctx) {
    const url = new URL(request.url)
    url.pathname = url.pathname.replace(/^\/api/, '') || '/'
    return app.fetch(new Request(url, request), env, ctx)
  }
}
